### ISSUE TITLE
Better docs for exposing ports to public

### ISSUE THREAD

**Issue by disconnect3d** [lukaszlach/clip#3]
There should be more information in the readme regarding exposing ports to the public i.e.:
- How does it work?
- What proxy/service does it use?
- How do I close and cleanup it? Do I need to explicitly remove the created network/bridge?
- Is it safe - does it use ONLY official docker images under the hood? (if not, it might be good to contribute further to do so). IMHO it could contain a warning that it might not be safe as you let others connect/run stuff on your local machine (if you do it from your desktop).

I agree ppl can see that in the code but I'd expect a good project to have such crucial info in the readme.

**Comment by lukaszlach** [comment]
The first three points are covered in the plugin documentation - https://github.com/lukaszlach/clip/tree/master/clips/expose
The last point is something I was also thinking about, dive and runlike are run from the official images (created by the authors of the respective tools), ngrok does not have an official image, I use the one I have been using since. It may be a good idea to create a dedicated image for this plugin.

**Comment by lukaszlach** [comment]
"expose" clip now uses an image from my namespace, until ngrok creates its own official one.
